[package]
name = "foo"
version = "0.1.0"
authors = ["Mike <mike706574@gmail.com>"]
license = "Eclipse Public License"

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
pretty_env_logger = "0.1"

[dev-dependencies]
num_cpus = "1.0"
spmc = "0.2"
